export enum Hat {
    UNEQUIP,
    BUSH,
    BERSERKER,
    JUNGLE,
    CRYSTAL,
    SPIKEGEAR,
    IMMUNITY,
    BOOST,
    APPLEHAT,
    SCUBA,
    HOOD,
    DEMOLIST,
}

export const Hats = [{
    bought: true,
    equipped: true,
    default: true,
    price: 0,
}, {
    image: 109,
    price: 250,
    axisY: 0,
    description: "Become a bush",
    name: "Bush Hat",
    bought: false,
    equipped: false,
    "rs": true
}, {
    image: 41,
    price: 5000,
    description: "Increased melee damage",
    axisY: 10,
    "cs": 1.25,
    speed: 0.85,
    name: "Berserker Gear",
    bought: false,
    equipped: false,
}, {
    image: 44,
    price: 3000,
    description: "Regenerate health",
    axisY: 13,
    "hs": 25,
    name: "Jungle Gear",
    bought: false,
    equipped: false,
}, {
    image: 45,
    price: 5000,
    description: "Receive reduced damage",
    axisY: 10,
    reduceDmg: 0.75,
    speed: 0.95,
    name: "Crystal Gear",
    bought: false,
    equipped: false,
}, {
    image: 48,
    price: 1000,
    description: "Attacker's receive damage",
    axisY: 10,
    reflect: 0.45,
    name: "Spike Gear",
    bought: false,
    equipped: false,
}, {
    image: 49,
    price: 4000,
    description: "Gain more health",
    axisY: 15,
    "ls": 150,
    reduceDmg: 0.75,
    name: "Immunity Gear",
    bought: false,
    equipped: false,
}, {
    image: 50,
    price: 1500,
    description: "Move quicker",
    axisY: 23,
    speed: 1.23,
    name: "Boost Hat",
    bought: false,
    equipped: false,
}, {
    image: 93,
    price: 150,
    description: "Apples become more succulent",
    axisY: 5,
    speed: 1.05,
    name: "Apple hat",
    bought: false,
    equipped: false,
}, {
    image: 121,
    price: 4000,
    description: "Move fast in ocean",
    axisY: 5,
    speed: 0.75,
    river: 1.5,
    name: "Scuba Gear",
    bought: false,
    equipped: false,
}, {
    image: 126,
    price: 3500,
    description: "Become invisible when still",
    axisY: 5,
    name: "Hood",
    bought: false,
    equipped: false,
    "rs": true
}, {
    image: 197,
    price: 4000,
    description: "Destroy buildings faster",
    axisY: 10,
    name: "Demolist",
    bought: false,
    equipped: false,
    speed: 0.3
}]