import { ArrElement } from "../types";

export enum ELayer {
    PLAYER,
    STONE,
    HARDSPIKE,
    TREE,
    GOLD,
    BUSH,
    TRAP,
    SPIKE,
    WOODWALL,
    PLATFORM,
    BOOST,
    LOOTBOX,
    PROJECTILE,
    WINDMILL,
    COW,
    SPAWN,
    POWERMILL,
    CASTLESPIKE,
    TURRET,
    WOODFARM,
    CHERRYWOODFARM,
    STONEWARM,
    CASTLEWALL,
    SHARK,
    WOLF,
    GOLDENCOW,
    ROOF,
    DRAGON,
    MAMMOTH,
    FIREBALL,
    CHEST,
    DRAGONWALLBIG,
    DRAGONWALLMEDIUM,
    DRAGONWALLSMALL,
    MAMMOTHWALL,
    MAMMOTHWALLSMALL,
    DUCK,
    TELEPORT,
    CACTUS,
    TORNADO
}

const LayerDataArray = [{
    id: ELayer.PLAYER,
    radius: 35,
    maxHealth: 100,
    "Qa": 1,
}, {
    id: ELayer.STONE,
    shoot: true,
    radius: 75,
    "Qa": 1,
    "Pa": 1,
}, {
    id: ELayer.HARDSPIKE,
    shoot: true,
    "qa": 35,
    radius: 45,
    maxHealth: 500,
    "Qa": 1,
}, {
    id: ELayer.TREE,
    shoot: true,
    cannotShoot: true,
    radius: 90,
    "Qa": 1,
    "Ka": 1,
}, {
    id: ELayer.GOLD,
    shoot: true,
    radius: 76,
    "Qa": 1,
    "Xa": 5,
}, {
    id: ELayer.BUSH,
    shoot: true,
    radius: 50,
    "Qa": 1,
    "Na": 1,
}, {
    id: ELayer.TRAP,
    radius: 40,
    maxHealth: 500,
    "Qa": 1,
}, {
    id: ELayer.SPIKE,
    shoot: true,
    "qa": 20,
    radius: 45,
    maxHealth: 375,
    "Ia": 20,
    "Qa": 1,
}, {
    id: ELayer.WOODWALL,
    shoot: true,
    radius: 45,
    maxHealth: 380,
    "Qa": 1,
}, {
    id: ELayer.PLATFORM,
    radius: 60,
    maxHealth: 300,
    "Qa": 1,
}, {
    id: ELayer.BOOST,
    radius: 40,
    maxHealth: 300,
    "Qa": 1,
}, {
    id: ELayer.LOOTBOX,
    radius: 40,
    maxHealth: 4,
    "Qa": 1,
}, {
    id: ELayer.PROJECTILE,
    radius: 0,
    maxHealth: 0,
}, {
    id: ELayer.WINDMILL,
    shoot: true,
    radius: 45,
    maxHealth: 400,
    rotateSpeed: Math.PI / 4,
    "Qa": 1,
}, {
    id: ELayer.COW,
    radius: 90,
    maxHealth: 380,
    animal: true,
    "Qa": 1,
    "Ja": 1.6,
    "$a": 9,
    "ts": 0,
}, {
    id: ELayer.SPAWN,
    shoot: true,
    radius: 50,
    maxHealth: 380,
    "Qa": 1,
}, {
    id: ELayer.POWERMILL,
    shoot: true,
    radius: 54,
    maxHealth: 400,
    rotateSpeed: Math.PI / 2,
    "Qa": 1,
}, {
    id: ELayer.CASTLESPIKE,
    shoot: true,
    "qa": 5,
    radius: 42,
    maxHealth: 1200,
    "Ia": 24,
    "Qa": 1,
}, {
    id: ELayer.TURRET,
    shoot: true,
    radius: 45,
    maxHealth: 800,
    "Qa": 1,
}, {
    id: ELayer.WOODFARM,
    shoot: true,
    cannotShoot: true,
    radius: 80,
    "Qa": 1,
    "Ka": 1,
}, {
    id: ELayer.CHERRYWOODFARM,
    shoot: true,
    cannotShoot: true,
    radius: 80,
    "Qa": 1,
    "Ka": 1,
}, {
    id: ELayer.STONEWARM,
    shoot: true,
    radius: 60,
    "Qa": 1,
    "Pa": 1,
}, {
    id: ELayer.CASTLEWALL,
    shoot: true,
    radius: 59,
    maxHealth: 1750,
    "Qa": 1,
}, {
    id: ELayer.SHARK,
    radius: 90,
    maxHealth: 380,
    animal: true,
    "Qa": 1,
    "Ja": 1.2,
    "$a": 49,
    "qa": 14,
    "ts": 3,
}, {
    id: ELayer.WOLF,
    radius: 50,
    maxHealth: 380,
    animal: true,
    "Qa": 1,
    "Ja": 1.6,
    "$a": 17,
    "qa": 14,
    "ts": 0,
}, {
    id: ELayer.GOLDENCOW,
    radius: 90,
    maxHealth: 1000,
    animal: true,
    "Qa": 1,
    "Ja": 1.6,
    "$a": 17,
    "qa": 19,
}, {
    id: ELayer.ROOF,
    radius: 50,
    maxHealth: 300,
    "Qa": 1,
}, {
    id: ELayer.DRAGON,
    radius: 100,
    maxHealth: 5000,
    animal: true,
    "Qa": 1,
    "Ja": 1.15,
    "$a": 17,
    "qa": 30,
    "ts": 0,
}, {
    id: ELayer.MAMMOTH,
    radius: 90,
    maxHealth: 5000,
    animal: true,
    "Qa": 1,
    "Ja": 1.6,
    "$a": 17,
    "qa": 30,
    "ts": 1,
}, {
    id: ELayer.FIREBALL,
    radius: 100,
    maxHealth: 380,
    "Qa": 1,
    "Ja": 0.4,
    "$a": 1,
    "qa": 15,
    "ts": 0,
}, {
    id: ELayer.CHEST,
    shoot: true,
    radius: 45,
    maxHealth: 380,
    "Qa": 1,
    "Xa": 50,
    "Lr": 20,
}, {
    id: ELayer.DRAGONWALLBIG,
    shoot: true,
    radius: 92,
    "Qa": 1,
    "Pa": 1,
}, {
    id: ELayer.DRAGONWALLMEDIUM,
    shoot: true,
    radius: 92,
    "Qa": 1,
    "Pa": 1,
}, {
    id: ELayer.DRAGONWALLSMALL,
    shoot: true,
    radius: 58,
    "Qa": 1,
    "Pa": 1,
}, {
    id: ELayer.MAMMOTHWALL,
    shoot: true,
    radius: 92,
    "Qa": 1,
    "Pa": 0,
}, {
    id: ELayer.MAMMOTHWALLSMALL,
    shoot: true,
    radius: 20,
    "Qa": 1,
    "Pa": 0,
}, {
    id: ELayer.DUCK,
    radius: 20,
    maxHealth: 380,
    animal: true,
    "Qa": 1,
    "Ja": 1.6,
    "$a": 9,
    "ts": 0,
}, {
    id: ELayer.TELEPORT,
    shoot: true,
    radius: 35,
    maxHealth: 150,
    "Qa": 1,
}, {
    id: ELayer.CACTUS,
    shoot: true,
    radius: 50,
    "Qa": 1,
    "Na": 5,
    "qa": 20,
}, {
    id: ELayer.TORNADO,
    radius: 220,
    rotateSpeed: Math.PI / 4,
    "Qa": 0,
    "Na": 5,
    "qa": 1,
}]

export const LayerData: Readonly<ArrElement<typeof LayerDataArray>>[] = LayerDataArray;

export const LayerObjects = LayerData.filter(layer => layer.shoot);
export const Animals = LayerData.filter(layer => layer.animal);